version: "3.9"

services:
  web_app:
    build: .
    container_name: web_api_application
    ports:
      - "5000:80"
    depends_on: 
      - database

  database:
    image: "postgres:latest"
    container_name: postgres_db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 5X0n00ziq3TovHbgjVmT1Hop4Zr2E7jA
        POSTGRES_DB: ViewDiagrams
    ports:
      - "5432:5432"
    volumes:
    - database-data:/var/lib/postgresql/data

volumes:
  database-data:  